#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi python run script for all direct examples
# comment/uncomment one of the following
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------

mpiexec -n 8  python ./linear-2nodes-no-overlap.py;
# mpiexec -n 4  python ./linear-2nodes-partial-overlap.py
# mpiexec -n 4  python ./linear-2nodes-total-overlap.py

mpiexec -n 12 python ./linear-3nodes-no-overlap.py;
# mpiexec -n 7  python ./linear-3nodes-partial-overlap.py
# mpiexec -n 4  python ./linear-3nodes-total-overlap.py

mpiexec -n 11 python ./cycle-4nodes-no-overlap.py;
