#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------
#ARCH=MAC_OSX
ARCH=LINUX
#ARCH=BGQ
#ARCH=FUSION
#ARCH=CRAY

# number of procs
num_procs=8

# executable
exe=./testcountoverflow

# nb items
items=500000000

#------
#
# run commands
#

if [ "$ARCH" = "MAC_OSX" ]; then

mpiexec -l -n $num_procs $exe $items

#dsymutil $exe ; mpiexec -l -n $num_procs xterm -e gdb -x gdb.run --args $exe

#dsymutil $exe ; mpiexec -n $num_procs valgrind -q $exe

#dsymutil $exe ; mpiexec -n $num_procs valgrind -q --leak-check=yes $exe 

fi

if [ "$ARCH" = "LINUX" ]; then

mpiexec -n $num_procs $exe $items

#mpiexec -n $num_procs xterm -e gdb -x gdb.run --args $exe

#mpiexec -n $num_procs valgrind -q $exe

#mpiexec -n $num_procs xterm -hold -e valgrind --suppressions=/home/matthieu/Dependencies/openmpi-1.8.7/install/share/openmpi/openmpi-valgrind.supp --suppressions=/home/matthieu/dumb/suppOpenMPI.txt --leak-check=yes $exe

fi

if [ "$ARCH" = "BGQ" ]; then

qsub -n $num_nodes --mode c$ppn -A SDAV -t 60 $exe 

fi

if [ "$ARCH" = "CRAY" ]; then

aprun -n $num_procs $exe

fi
