#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------
#ARCH=MAC_OSX
ARCH=LINUX
#ARCH=BGQ
#ARCH=FUSION
#ARCH=CRAY

# number of procs
np1=8
np2=4
np3=2
np4=2
np5=2
num_procs=$[$np1 + $np2 + $np3 + $np4 + $np5]

# procs per node
ppn=1 # adjustable for BG/Q, allowed 1, 2, 4, 8, 16, 32, 64

# number of nodes
num_nodes=$[$num_procs / $ppn]
if [ $num_nodes -lt 1 ]; then
    num_nodes=1
fi

# executables
exe1=./points
exe2=./pts_dflow
exe3=./tess
exe4=./pts_dflow
exe5=./dense

# mpmd command
mpmd="-n $np1 $exe1 : -n $np2 $exe2 : -n $np3 $exe3 : -n $np4 $exe4 : -n $np5 $exe5"

#------
#
# run commands
#

if [ "$ARCH" = "MAC_OSX" ]; then

mpiexec -l $mpmd

fi

if [ "$ARCH" = "LINUX" ]; then

mpiexec -l $mpmd

fi

if [ "$ARCH" = "BGQ" ]; then

# temporary fix, should be in the bgclang wrapper instead
# don't set this in .bashrc for the login node; bad things happen
# only set it here so that it goes straight to the compute node
my_LD_LIBRARY_PATH=/bgsys/drivers/toolchain/V1R2M4_base_4.7.2/gnu-linux-4.7.2/powerpc64-bgq-linux/lib:$LD_LIBRARY_PATH

# TODO: fixme
# BGQ mpmd mode is done differently
qsub -n $num_nodes --env LD_LIBRARY_PATH=$my_LD_LIBRARY_PATH:DECAF_PREFIX=$DECAF_PREFIX --mode c$ppn -A SDAV -t 60 $mpmd

fi

if [ "$ARCH" = "CRAY" ]; then
echo "TODO"
fi
