#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi python run script for all direct examples
# comment/uncomment one of the following
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------

mpiexec -n 8  python ./lammps-2nodes.py
# mpiexec -n 8  python ./lammps-3nodes-2cons.py
# mpiexec -n 10 python ./lammps-4nodes.py

