#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi python run script for all direct examples
# comment/uncomment one of the following
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------

mpiexec \
    -n 4  python ./linear_2nodes_prod.py : \
    -n 2 python ./linear_2nodes_dflow.py : \
    -n 2 python ./linear_2nodes_con.py
