//---------------------------------------------------------------------------
//
// example of direct coupling
//
// Tom Peterka
// Argonne National Laboratory
// 9700 S. Cass Ave.
// Argonne, IL 60439
// tpeterka@mcs.anl.gov
//
//--------------------------------------------------------------------------
#include <decaf/decaf.hpp>

#include <assert.h>
#include <mpi.h>

// user-defined producer code
void prod_code(void* args)
{
}
// user-defined selector code
void con_code(void* args)
{
}
// user-defined selector code
void sel_type(void *args)
{
}
// user-defined pipeliner code
void pipe_type(void *args)
{
}
// user-defined aggregator code
void aggr_type(void *args)
{
}
// user-defined resilience code
void fault_check(void *args)
{
}

int main(int argc, char** argv)
{

  MPI_Init(&argc, &argv);

  // create (split) new communicators
  int prod_size = 4;  // fake some communicator sizes: producer
  int con_size = 2;   // consumer
  int dflow_size = 1; // dataflow size defines number of aggregator and other intermediate nodes
  int tot_time_steps = 100; // total time steps
  int con_interval = 10; // consumer frequency (in time steps)
  void* data; // pointer to base address of data generated by producer

  // start decaf, allocate on the heap instead of on the stack so that it can be deleted
  // before MPI_Finalize is called at the end
  decaf::Decaf* decaf = new decaf::Decaf(MPI_COMM_WORLD, prod_size, con_size, dflow_size);
  decaf->err();

  // producer
  if (decaf->type() == DECAF_PRODUCER_COMM)
  {
    decaf::Data prod_data;
    decaf::Producer prod(decaf->comm(), &prod_code, prod_data);
    // produce
    for (int t = 0; t < tot_time_steps; t++)
        prod.exec(data);
  }

  // consumer
  else if (decaf->type() == DECAF_CONSUMER_COMM)
  {
    decaf::Data con_data;
    decaf::Consumer con(decaf->comm(),
                        &con_code,
                        &sel_type,
                        &pipe_type,
                        &aggr_type,
                        &fault_check,
                        con_data);
  }

  // dataflow
  else if (decaf->type() == DECAF_DATAFLOW_COMM)
    decaf::Dataflow dflow();

  delete decaf;
  MPI_Finalize();
}
