#!/bin/bash

#----------------------------------------------------------------------------
#
# mpi run script
#
# Tom Peterka
# Argonne National Laboratory
# 9700 S. Cass Ave.
# Argonne, IL 60439
# tpeterka@mcs.anl.gov
#
#----------------------------------------------------------------------------
#ARCH=MAC_OSX
ARCH=LINUX
#ARCH=BGQ
#ARCH=FUSION
#ARCH=CRAY

# number of procs
num_procs=12

# procs per node
ppn=1 # adjustable for BG/Q, allowed 1, 2, 4, 8, 16, 32, 64

# number of nodes
num_nodes=$[$num_procs / $ppn]
if [ $num_nodes -lt 1 ]; then
    num_nodes=1
fi

# executable
exe=./linear_3nodes

#------
#
# run commands
#

if [ "$ARCH" = "MAC_OSX" ]; then

mpiexec -l -n $num_procs $exe

#dsymutil $exe ; mpiexec -l -n $num_procs xterm -e lldb --args $exe

#dsymutil $exe ; mpiexec -n $num_procs valgrind -q $exe

#dsymutil $exe ; mpiexec -n $num_procs valgrind -q --leak-check=yes $exe

fi

if [ "$ARCH" = "LINUX" ]; then

mpiexec -n $num_procs $exe

#mpiexec -n $num_procs xterm -e gdb -x gdb.run --args $exe

#mpiexec -n $num_procs valgrind -q $exe

#mpiexec -n $num_procs valgrind -q --leak-check=yes $exe

fi

if [ "$ARCH" = "BGQ" ]; then

# temporary fix, should be in the bgclang wrapper instead
# don't set this in .bashrc for the login node; bad things happen
# only set it here so that it goes straight to the compute node
my_LD_LIBRARY_PATH=/bgsys/drivers/toolchain/V1R2M4_base_4.7.2/gnu-linux-4.7.2/powerpc64-bgq-linux/lib:$LD_LIBRARY_PATH


qsub -n $num_nodes --env LD_LIBRARY_PATH=$my_LD_LIBRARY_PATH:DECAF_PREFIX=$DECAF_PREFIX --mode c$ppn -A SDAV -t 60 $exe

# how to trace ld paths for debugging dynamic libraries not being found
# qsub -n $num_nodes --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:LD_DEBUG=libs:LD_VERBOSE=1:LD_TRACE_LOADED_OBJECTS=1 --mode c$ppn -A SDAV -t 60 $exe

fi

if [ "$ARCH" = "CRAY" ]; then

aprun -n $num_procs $exe

fi
